insert into public.site_config (key, value, label, type, description, is_public) values
('about_address_label', 'Address', 'About address label', 'text', 'Label used in the About summary rail for address.', true),
('about_eyebrow', 'About the kitchen', 'About eyebrow', 'text', 'Eyebrow on the About page.', true),
('about_hero_copy', 'A warm, editorial storefront for a pizzeria that wants the ordering experience to feel premium and easy.', 'About hero copy', 'textarea', 'About page hero copy.', true),
('about_hours_label', 'Hours', 'About hours label', 'text', 'Label used in the About summary rail for hours.', true),
('about_location_title', 'Location', 'About location title', 'text', 'About page location card title.', true),
('about_map_action_label', 'Open map', 'About map action', 'text', 'Link label for the about page map block.', true),
('about_map_missing_copy', 'Map link is set in the store settings.', 'About map missing copy', 'textarea', 'Copy shown when the map link is missing.', true),
('about_min_order_label', 'Min order', 'About min order label', 'text', 'Label used in the About summary rail for minimum order.', true),
('about_notice', 'Fresh ingredients, live data, and a WhatsApp-first ordering experience.', 'About notice', 'textarea', 'About page callout.', true),
('about_recipe_body', 'Built for real operations.', 'About recipe body', 'text', 'About page card body.', true),
('about_recipe_copy', 'The storefront reads categories, pizzas, toppings, extras, addons, desserts, notifications, and site config live from the database.', 'About recipe copy', 'textarea', 'About page card copy.', true),
('about_recipe_title', 'Recipe', 'About recipe title', 'text', 'About page card title.', true),
('about_workflow_body', 'Primary order path is WhatsApp.', 'About workflow body', 'text', 'About page workflow card body.', true),
('about_workflow_copy', 'The order is stored in the database first, then the customer is taken to WhatsApp with the message already composed.', 'About workflow copy', 'textarea', 'About page workflow card copy.', true),
('about_workflow_title', 'Workflow', 'About workflow title', 'text', 'About page workflow card title.', true),
('address_line1', 'Carona, Goa', 'Address line 1', 'text', 'First line of the public address.', true),
('address_line2', '', 'Address line 2', 'text', 'Optional second line of the public address.', true),
('announcement_bar', 'Freshly made daily with premium ingredients and live order handling.', 'Announcement bar', 'text', 'Short announcement shown at the top of the site.', true),
('brand_logo_image_url', '', 'Brand logo image', 'image', 'Shown in the top-left brand area and mobile drawer when set. Leave blank to use the text mark.', true),
('brand_tagline', 'Crafted pizza house', 'Brand tagline', 'text', 'Small supporting tagline next to the logo.', true),
('build_hero_copy', 'Pick a base recipe, choose a size, layer in extra toppings, then send the final order to WhatsApp with the exact details preserved in the cart.', 'Builder hero copy', 'textarea', 'Top copy on the builder page.', true),
('build_hero_title', 'Build a custom pizza without leaving the menu.', 'Builder hero title', 'text', 'Top title on the builder page.', true),
('builder_add_custom_label', 'Add custom pizza', 'Add custom label', 'text', 'Primary builder CTA when ordering is open.', true),
('builder_add_to_cart_label', 'Add to cart', 'Add to cart label', 'text', 'Primary builder CTA text.', true),
('builder_back_to_menu_label', 'Back to menu', 'Back to menu label', 'text', 'Button label returning to the menu.', true),
('builder_base_pizza_label', 'Base pizza', 'Base pizza label', 'text', 'Label for the pizza selector.', true),
('builder_extras_label', 'Extras', 'Extras label', 'text', 'Label for the extras row.', true),
('builder_eyebrow', 'Pizza builder', 'Builder eyebrow', 'text', 'Eyebrow at the top of the builder page.', true),
('builder_hero_image_url', '', 'Pizza builder image', 'image', 'Shown in the pizza builder preview when the selected pizza does not have its own image.', true),
('builder_no_pizzas_body', 'The menu is empty or all pizzas are disabled.', 'No pizzas body', 'textarea', 'Body shown when no pizzas exist.', true),
('builder_no_pizzas_title', 'No pizzas are currently available.', 'No pizzas title', 'text', 'Title shown when no pizzas exist.', true),
('builder_notes_label', 'Notes', 'Notes label', 'text', 'Label for the notes textarea.', true),
('builder_notes_placeholder', 'Sauce preference, crust notes, or any special instruction', 'Notes placeholder', 'textarea', 'Placeholder for builder notes.', true),
('builder_notice_copy', 'Builder selections flow directly into the cart and order handoff.', 'Builder notice copy', 'textarea', 'Builder notice copy.', true),
('builder_paused_notice_copy', 'The storefront is paused, so builder changes will wait until the store reopens.', 'Builder paused notice', 'textarea', 'Builder paused notice copy.', true),
('builder_preview_copy', 'A live recipe from the menu.', 'Preview copy', 'textarea', 'Preview card copy on the builder page.', true),
('builder_quantity_label', 'Quantity', 'Quantity label', 'text', 'Label for the quantity input.', true),
('builder_size_label', 'Size', 'Size label', 'text', 'Label for the size selector.', true),
('builder_summary_base_label', 'Base pizza', 'Summary base label', 'text', 'Summary label for the base pizza.', true),
('builder_summary_copy', 'This is the exact payload that lands in the cart and final handoff.', 'Summary copy', 'textarea', 'Builder summary copy.', true),
('builder_summary_extras_label', 'Extras', 'Summary extras label', 'text', 'Summary label for extras.', true),
('builder_summary_none_label', 'None', 'Summary none label', 'text', 'Summary label when no extras are selected.', true),
('builder_summary_quantity_label', 'Quantity', 'Summary quantity label', 'text', 'Summary label for quantity.', true),
('builder_summary_size_label', 'Size', 'Summary size label', 'text', 'Summary label for the size.', true),
('builder_summary_title', 'Live summary', 'Summary title', 'text', 'Builder summary title.', true),
('builder_summary_total_label', 'Total', 'Summary total label', 'text', 'Summary label for the total price.', true),
('builder_view_status_label', 'View live status', 'View status label', 'text', 'Button label when ordering is paused.', true),
('cart_back_to_menu_label', 'Back to menu', 'Back to menu label', 'text', 'Button label returning to the menu from handoff.', true),
('cart_continue_browsing_label', 'Continue browsing', 'Continue browsing label', 'text', 'Button label for returning to the menu.', true),
('cart_customer_name_label', 'Name', 'Customer name label', 'text', 'Label for the customer name field.', true),
('cart_customer_name_placeholder', 'Customer name', 'Customer name placeholder', 'text', 'Placeholder for the customer name field.', true),
('cart_customer_phone_label', 'Phone', 'Customer phone label', 'text', 'Label for the customer phone field.', true),
('cart_customer_phone_placeholder', '+91 ...', 'Customer phone placeholder', 'text', 'Placeholder for the customer phone field.', true),
('cart_delivery_address_label', 'Delivery address', 'Delivery address label', 'text', 'Label for the delivery address field.', true),
('cart_delivery_address_placeholder', 'House, street, landmark', 'Delivery placeholder', 'textarea', 'Placeholder for the delivery address field.', true),
('cart_delivery_option_label', 'Delivery', 'Delivery option label', 'text', 'Delivery option label.', true),
('cart_empty_copy', 'Your cart is empty. Add items from Menu or Build first.', 'Empty cart copy', 'textarea', 'Empty cart message.', true),
('cart_empty_summary_copy', 'Add items from Menu or Build first.', 'Empty summary copy', 'textarea', 'Body shown when the cart has no items.', true),
('cart_empty_summary_title', 'Your cart is empty', 'Empty summary title', 'text', 'Title shown when the cart has no items.', true),
('cart_eyebrow', 'WhatsApp checkout', 'Cart eyebrow', 'text', 'Eyebrow on the cart page.', true),
('cart_fulfillment_label', 'Fulfillment', 'Fulfillment label', 'text', 'Label for the fulfillment selector.', true),
('cart_general_error_message', 'We could not place the order.', 'General error message', 'textarea', 'Fallback error message for checkout failures.', true),
('cart_handoff_open_pc_copy', 'Open on this computer', 'Handoff open PC copy', 'text', 'Copy shown below the QR block.', true),
('cart_handoff_order_prefix', 'Order #', 'Handoff order prefix', 'text', 'Prefix before the order number.', true),
('cart_handoff_ready_copy', 'The order is saved and ready to send.', 'Handoff ready copy', 'textarea', 'Copy shown when the order is ready to send.', true),
('cart_handoff_title', 'Send from your phone', 'Handoff title', 'text', 'Title above the post-checkout handoff.', true),
('cart_hero_copy', 'This checkout keeps WhatsApp as the primary customer action while storing the same order for kitchen visibility and reporting.', 'Cart hero copy', 'textarea', 'Hero supporting copy on the cart page.', true),
('cart_hero_image_url', '', 'Cart hero image', 'image', 'Shown beside the checkout summary before the WhatsApp handoff.', true),
('cart_hero_title', 'Send the order on WhatsApp and keep moving.', 'Cart hero title', 'text', 'Main title on the cart page.', true),
('cart_hours_copy', 'Store hours:', 'Hours label', 'text', 'Prefix text before hours.', true),
('cart_item_kind_addon_label', 'Addon', 'Addon kind label', 'text', 'Label for addon items in the cart summary.', true),
('cart_item_kind_dessert_label', 'Dessert', 'Dessert kind label', 'text', 'Label for dessert items in the cart summary.', true),
('cart_item_kind_extra_label', 'Extra', 'Extra kind label', 'text', 'Label for extra items in the cart summary.', true),
('cart_item_kind_pizza_label', 'Pizza', 'Pizza kind label', 'text', 'Label for pizza items in the cart summary.', true),
('cart_items_count_label', 'Items', 'Items count label', 'text', 'Label for the item count row.', true),
('cart_items_label', 'Cart items', 'Cart items label', 'text', 'Title above the line item list.', true),
('cart_minimum_copy', 'Minimum order', 'Minimum label', 'text', 'Prefix text before the minimum order amount.', true),
('cart_minimum_not_set_label', 'not set', 'Minimum not set label', 'text', 'Text shown when no minimum order is configured.', true),
('cart_missing_address_message', 'Please add a delivery address or switch to pickup.', 'Missing address message', 'textarea', 'Validation error when a delivery address is missing.', true),
('cart_missing_customer_message', 'Please fill the customer details before sending the order.', 'Missing customer message', 'textarea', 'Validation error when customer details are incomplete.', true),
('cart_next_step_copy', 'Scan the QR or open the link', 'Next step copy', 'textarea', 'Copy for the next step block.', true),
('cart_next_step_label', 'Next step', 'Next step label', 'text', 'Label for the next step block.', true),
('cart_notes_label', 'Notes', 'Notes label', 'text', 'Label for the order notes field.', true),
('cart_notes_placeholder', 'Allergies, sauce preference, or timing notes', 'Notes placeholder', 'textarea', 'Placeholder for the order notes field.', true),
('cart_open_order_chat_label', 'Open order chat', 'Open order chat label', 'text', 'Button label to open the chat on mobile.', true),
('cart_open_pc_label', 'Open on this computer', 'Open on PC label', 'text', 'Button label to open the chat on desktop.', true),
('cart_order_number_label', 'Order number', 'Order number label', 'text', 'Label for the order number.', true),
('cart_order_saved_copy', 'The order is saved for kitchen tracking and reporting before the handoff opens.', 'Order saved copy', 'textarea', 'Footnote shown after checkout.', true),
('cart_order_saved_label', 'The order is saved and ready to send.', 'Order saved label', 'text', 'Success block title after checkout.', true),
('cart_order_summary_title', 'Order summary', 'Order summary title', 'text', 'Title above the cart summary list.', true),
('cart_paused_closed_message', 'Orders are currently closed. Please try again when the store is open.', 'Closed paused message', 'textarea', 'Message shown when checkout is paused because the store is closed.', true),
('cart_paused_maintenance_message', 'Orders are paused while the storefront is in maintenance mode.', 'Maintenance paused message', 'textarea', 'Message shown when checkout is paused for maintenance.', true),
('cart_pickup_note_label', 'Pickup note', 'Pickup note label', 'text', 'Label for the pickup note field.', true),
('cart_pickup_note_placeholder', 'Pickup timing or note', 'Pickup placeholder', 'textarea', 'Placeholder for the pickup note field.', true),
('cart_pickup_option_label', 'Pickup', 'Pickup option label', 'text', 'Pickup option label.', true),
('cart_pizza_summary_template', '{count} pizza{plural} across {sizes}', 'Pizza summary template', 'text', 'Template for the cart size summary line.', true),
('cart_place_order_label', 'Place order', 'Place order label', 'text', 'Submit button label.', true),
('cart_preview_copy', 'Orders are stored in the system and sent to WhatsApp with the full payload intact.', 'Cart preview copy', 'textarea', 'Preview card supporting copy.', true),
('cart_preview_image_alt', 'Live menu preview', 'Preview image alt', 'text', 'Alt text for the cart preview image.', true),
('cart_preview_title', 'Your cart is ready', 'Cart preview title', 'text', 'Preview card title.', true),
('cart_qr_alt_prefix', 'QR code for order', 'QR alt prefix', 'text', 'Alt prefix for the QR code image.', true),
('cart_remove_label', 'Remove', 'Remove label', 'text', 'Label for removing an item.', true),
('cart_scan_qr_label', 'Scan the QR code with your phone to open the exact order message, then send it from there.', 'QR label', 'textarea', 'Helper copy for the QR block.', true),
('cart_sending_label', 'Sending...', 'Sending label', 'text', 'Submit button label while sending.', true),
('cart_size_summary_label', 'Pizza sizes in cart', 'Size summary label', 'text', 'Label above the size count pills.', true),
('cart_subtotal_label', 'Subtotal', 'Subtotal label', 'text', 'Label for the subtotal row.', true),
('cart_view_live_status_label', 'View live status', 'View live status label', 'text', 'Button label used when ordering is paused.', true),
('cart_view_status_label', 'View status', 'View status label', 'text', 'Button label to view live status from handoff.', true),
('closing_time', '23:00', 'Closing time', 'time', 'Closing time used across the storefront.', true),
('contact_address_label', 'Address', 'Contact address label', 'text', 'Label used in the Contact summary rail for address.', true),
('contact_email_copy', 'This can be connected later if you want a public inbox on the site.', 'Contact email copy', 'textarea', 'Contact email card copy.', true),
('contact_email_title', 'Email', 'Contact email title', 'text', 'Contact email card title.', true),
('contact_eyebrow', 'Contact', 'Contact eyebrow', 'text', 'Eyebrow shown on the Contact page.', true),
('contact_hero_copy', 'Orders, delivery questions, and special notes all work best through WhatsApp. This page exists for convenience and trust.', 'Contact hero copy', 'textarea', 'Contact page supporting copy.', true),
('contact_hero_title', 'Talk to the kitchen directly.', 'Contact hero title', 'text', 'Contact page title.', true),
('contact_hours_label', 'Hours', 'Contact hours label', 'text', 'Label used in the Contact summary rail for hours.', true),
('contact_map_action_label', 'Open in Maps', 'Contact map action', 'text', 'Link label for the contact map block.', true),
('contact_map_body', 'Find us easily.', 'Contact map body', 'text', 'Contact map card body.', true),
('contact_map_missing_copy', 'Set the maps link from the store settings.', 'Contact map missing copy', 'textarea', 'Copy shown when the map link is missing on the contact page.', true),
('contact_map_title', 'Map', 'Contact map title', 'text', 'Contact map card title.', true),
('contact_message_label', 'Message us', 'Contact message label', 'text', 'Button label for the contact action.', true),
('contact_ordering_body', 'WhatsApp-first.', 'Contact ordering body', 'text', 'Contact ordering card body.', true),
('contact_ordering_copy', 'The order is stored and then handed off to WhatsApp, which keeps the customer flow low-friction.', 'Contact ordering copy', 'textarea', 'Contact ordering card copy.', true),
('contact_ordering_title', 'Live ordering', 'Contact ordering title', 'text', 'Contact ordering card title.', true),
('contact_whatsapp_label', 'WhatsApp', 'Contact WhatsApp label', 'text', 'Label used in the Contact summary rail for WhatsApp.', true),
('dashboard_live_mode', 'true', 'Dashboard Live Mode', 'boolean', 'Controls the live indicator and dashboard shell sync state.', false),
('delivery_address_title', 'Address', 'Delivery address title', 'text', 'Delivery address card title.', true),
('delivery_eyebrow', 'Delivery info', 'Delivery eyebrow', 'text', 'Eyebrow shown on the Delivery page.', true),
('delivery_hero_copy', 'Hours, address, and minimums are pulled from the store settings.', 'Delivery hero copy', 'textarea', 'Delivery page supporting copy.', true),
('delivery_hero_title', 'Delivery that is clear before the order starts.', 'Delivery hero title', 'text', 'Delivery page title.', true),
('delivery_hours_copy', 'If the store is closed, the open/closed state comes from the live settings.', 'Delivery hours copy', 'textarea', 'Delivery hours card copy.', true),
('delivery_hours_title', 'Hours', 'Delivery hours title', 'text', 'Delivery hours card title.', true),
('delivery_map_action_label', 'Open map', 'Delivery map action', 'text', 'Link label for the delivery map block.', true),
('delivery_map_missing_copy', 'Map link is managed from the store settings.', 'Delivery map missing copy', 'textarea', 'Copy shown when the map link is missing on the delivery page.', true),
('delivery_min_copy', 'Shown in cart before checkout, so there are no surprises.', 'Delivery minimum copy', 'textarea', 'Delivery minimum card copy.', true),
('delivery_min_title', 'Minimum', 'Delivery minimum title', 'text', 'Delivery minimum card title.', true),
('delivery_order_chat_label', 'Open order chat', 'Delivery chat label', 'text', 'Button label for the delivery page chat action.', true),
('faq_back_to_menu_label', 'Back to menu', 'FAQ back button', 'text', 'Button label returning to the menu from the FAQ page.', true),
('faq_eyebrow', 'FAQ', 'FAQ eyebrow', 'text', 'Eyebrow shown on the FAQ page.', true),
('faq_hero_copy', 'Short answers, no noise, and the same live storefront data underneath.', 'FAQ hero copy', 'textarea', 'FAQ page supporting copy.', true),
('faq_hero_title', 'Everything customers usually ask.', 'FAQ hero title', 'text', 'FAQ page title.', true),
('faq_items', '[{"title":"How do I order?","body":"Build your cart, go to checkout, and complete the handoff. The same order is stored for the kitchen as well."},{"title":"Can I customize pizzas?","body":"Yes. Use the Build page to choose size, extras, and notes for a custom pizza."},{"title":"Do you take offline orders?","body":"The storefront uses a lightweight order handoff so the flow stays simple for the kitchen and the customer."},{"title":"What happens if an item is sold out?","body":"Sold-out items are hidden or marked unavailable based on the live menu state."}]', 'FAQ Items', 'json', 'Structured FAQ blocks', true),
('footer_copy', 'A premium storefront for pizza, crafted to feel warm, cinematic, and easy to order from.', 'Footer copy', 'textarea', 'Brand copy shown in the footer.', true),
('google_maps_link', '', 'Google Maps link', 'url', 'Link to your business location.', true),
('hero_subtitle', 'Hand-tossed pizza, warm sides, and a WhatsApp-first order flow built for real life.', 'Default hero subtitle', 'textarea', 'Fallback hero subtitle used across the storefront.', true),
('hero_title', 'We Knead Pizza', 'Default hero title', 'text', 'Fallback title used when a page-specific title is not set.', true),
('home_announcement', 'Freshly made daily.', 'Homepage announcement', 'text', 'Eyebrow announcement at the top of the home page.', true),
('home_closing_eyebrow', 'Tonight''s move', 'Closing eyebrow', 'text', 'Closing banner eyebrow.', true),
('home_closing_primary_cta', 'Start with menu', 'Closing CTA 1', 'text', 'First closing banner CTA.', true),
('home_closing_primary_paused_label', 'View live status', 'Closing primary paused label', 'text', 'Closing button label when ordering is paused.', true),
('home_closing_secondary_cta', 'Build custom', 'Closing CTA 2', 'text', 'Second closing banner CTA.', true),
('home_closing_secondary_paused_label', 'Plan ahead', 'Closing secondary paused label', 'text', 'Closing secondary label when ordering is paused.', true),
('home_closing_title', 'Pick a craving and let the site do the rest', 'Closing title', 'text', 'Closing banner title.', true),
('home_feature_copy', 'Rich, hot, and ready to slide from discovery to order with almost no friction.', 'Feature copy', 'textarea', 'Featured pizza callout on the homepage.', true),
('home_feature_eyebrow_label', 'Chef''s pick', 'Feature eyebrow label', 'text', 'Label shown above the home hero showcase.', true),
('home_feature_fallback_title', 'Signature pizza', 'Hero fallback title', 'text', 'Fallback title shown in the hero showcase.', true),
('home_feature_image_url', '', 'Home feature image', 'image', 'Shown in the homepage hero showcase and featured media panel.', true),
('home_feature_paused_label', 'View live status', 'Hero paused label', 'text', 'Primary label on the hero showcase button when ordering is paused.', true),
('home_feature_primary_label', 'Checkout now', 'Hero primary label', 'text', 'Primary label on the hero showcase button.', true),
('home_hero_build_label', 'Build your pizza', 'Hero build label', 'text', 'Secondary action label in the hero button row.', true),
('home_hero_checkout_label', 'Checkout now', 'Hero checkout label', 'text', 'Third action label in the hero button row.', true),
('home_hero_menu_label', 'Browse the menu', 'Hero menu label', 'text', 'Primary action label in the hero button row.', true),
('home_hero_subtitle', 'Hand-tossed pizza, warm sides, and a WhatsApp-first order flow.', 'Hero subtitle', 'textarea', 'Homepage hero subtitle.', true),
('home_hero_title', 'We Knead Pizza', 'Hero title', 'text', 'Main title on the homepage.', true),
('home_orbit_minimum_label', 'Minimum', 'Orbit minimum label', 'text', 'Label in the hero orbit block for minimum order.', true),
('home_orbit_state_label', 'State', 'Orbit state label', 'text', 'Label in the hero orbit block for state.', true),
('home_orbit_tonight_label', 'Tonight', 'Orbit tonight label', 'text', 'Label in the hero orbit block for tonight.', true),
('home_showcase_pair_label', 'Pair it with', 'Showcase pair label', 'text', 'Label shown in the hero showcase stack.', true),
('home_signature_copy', 'A curated line-up that feels more like browsing a chef''s counter than a spreadsheet.', 'Signature copy', 'textarea', 'Signature section supporting copy.', true),
('home_signature_details_label', 'Details', 'Signature details label', 'text', 'Label for the featured card details button.', true),
('home_signature_eyebrow', 'Signature picks', 'Signature eyebrow', 'text', 'Section label above the featured pizzas.', true),
('home_signature_fallback_copy', 'A crowd-pleasing favorite from the live menu.', 'Signature fallback copy', 'textarea', 'Fallback copy shown on featured cards.', true),
('home_signature_order_label', 'Order', 'Signature order label', 'text', 'Label for the featured card order button.', true),
('home_signature_tag_bestseller_label', 'Bestseller', 'Signature bestseller tag', 'text', 'Tag used on featured cards when an item is a bestseller.', true),
('home_signature_tag_signature_label', 'Signature', 'Signature tag', 'text', 'Tag used on featured cards when an item is not a bestseller.', true),
('home_signature_title', 'Tap a favorite, feel the rhythm, and order', 'Signature title', 'text', 'Signature section title.', true),
('home_step_1_copy', 'Scroll the menu and tap into a signature pizza in seconds.', 'Step 1 copy', 'textarea', 'First intro card copy.', true),
('home_step_1_href', '/menu', 'Step 1 link', 'url', 'First intro card link.', true),
('home_step_1_label', 'Browse menu', 'Step 1 button', 'text', 'First intro card button label.', true),
('home_step_1_title', 'Crave something now', 'Step 1 title', 'text', 'First intro card title.', true),
('home_step_2_copy', 'Start with a base, add extras, and build the exact bite you want.', 'Step 2 copy', 'textarea', 'Second intro card copy.', true),
('home_step_2_href', '/build', 'Step 2 link', 'url', 'Second intro card link.', true),
('home_step_2_label', 'Build custom', 'Step 2 button', 'text', 'Second intro card button label.', true),
('home_step_2_title', 'Make it yours', 'Step 2 title', 'text', 'Second intro card title.', true),
('home_step_3_copy', 'Checkout flows straight into WhatsApp with a clean order summary.', 'Step 3 copy', 'textarea', 'Third intro card copy.', true),
('home_step_3_href', '/cart', 'Step 3 link', 'url', 'Third intro card link.', true),
('home_step_3_label', 'Review cart', 'Step 3 button', 'text', 'Third intro card button label when ordering is open.', true),
('home_step_3_paused_copy', 'The storefront summary explains the live state.', 'Step 3 paused copy', 'textarea', 'Third intro card copy when ordering is paused.', true),
('home_step_3_paused_label', 'View live status', 'Step 3 paused button', 'text', 'Third intro card button label when ordering is paused.', true),
('home_step_3_paused_title', 'Check live status', 'Step 3 paused title', 'text', 'Third intro card title when ordering is paused.', true),
('home_step_3_title', 'Send it fast', 'Step 3 title', 'text', 'Third intro card title.', true),
('home_steps_cta', 'View all items', 'Steps CTA', 'text', 'CTA button beside the intro cards.', true),
('home_steps_eyebrow', 'Start here', 'Steps eyebrow', 'text', 'Label above the intro cards.', true),
('home_steps_title', 'A three-step flow people actually enjoy using', 'Steps title', 'text', 'Headline above the intro cards.', true),
('is_open', 'false', 'Accepting Orders', 'boolean', 'Toggle to allow new orders on the storefront.', true),
('menu_browse_label', 'Browse the menu', 'Browse label', 'text', 'Label above the browser section.', true),
('menu_card_add_template', 'Add {size}', 'Add template', 'text', 'Button template for adding a size.', true),
('menu_card_add_to_cart_label', 'Add to cart', 'Add to cart label', 'text', 'Button label used for non-pizza cards.', true),
('menu_card_addon_copy', 'Flat-price side item', 'Addon copy', 'textarea', 'Fallback copy for addon cards.', true),
('menu_card_addon_kind_label', 'Addon', 'Addon kind label', 'text', 'Kind label for addon cards.', true),
('menu_card_bestseller_label', 'Bestseller', 'Card bestseller label', 'text', 'Badge for bestselling items.', true),
('menu_card_cart_aria_label', 'Pizza sizes already in cart', 'Cart aria label', 'text', 'Accessible label above the cart size counts.', true),
('menu_card_dessert_copy', 'Sweet finish to the meal', 'Dessert copy', 'textarea', 'Fallback copy for dessert cards.', true),
('menu_card_dessert_kind_label', 'Dessert', 'Dessert kind label', 'text', 'Kind label for dessert cards.', true),
('menu_card_details_label', 'Details', 'Details label', 'text', 'Button label for item details.', true),
('menu_card_extra_copy', 'Sized topping add-on', 'Extra copy', 'textarea', 'Fallback copy for extra cards.', true),
('menu_card_extra_kind_label', 'Extra', 'Extra kind label', 'text', 'Kind label for extra cards.', true),
('menu_card_house_recipe_copy', 'House recipe from the live menu.', 'House recipe copy', 'textarea', 'Fallback copy for pizza cards.', true),
('menu_card_in_cart_label', 'In cart', 'In cart label', 'text', 'Label above the cart counts.', true),
('menu_card_new_label', 'New', 'Card new label', 'text', 'Badge for new items.', true),
('menu_card_nonveg_label', 'Non-veg', 'Card non-veg label', 'text', 'Badge for non-veg items.', true),
('menu_card_ordering_paused_label', 'Ordering paused', 'Ordering paused label', 'text', 'Button label when ordering is paused.', true),
('menu_card_pick_size_label', 'Pick a size', 'Pick size label', 'text', 'Label above size selection.', true),
('menu_card_price_note_template', '{size} size, ready to add', 'Price note template', 'text', 'Template shown under the selected price.', true),
('menu_card_selected_price_label', 'Selected price', 'Selected price label', 'text', 'Label above the selected size price.', true),
('menu_card_soldout_label', 'Sold out', 'Card sold out label', 'text', 'Badge for sold out items.', true),
('menu_card_spicy_label', 'Spicy', 'Card spicy label', 'text', 'Badge for spicy items.', true),
('menu_card_veg_label', 'Veg', 'Card veg label', 'text', 'Badge for vegetarian items.', true),
('menu_counts_template', '{pizzas} pizzas, {addons} addons, {extras} extras, {desserts} desserts', 'Counts template', 'text', 'Summary string shown above the menu grid.', true),
('menu_detail_action_copy', 'Use the main menu or builder to add this item to your cart.', 'Action copy', 'textarea', 'Action card supporting text.', true),
('menu_detail_action_title', 'Action', 'Action title', 'text', 'Action card title.', true),
('menu_detail_add_from_menu_label', 'Add from menu', 'Add from menu label', 'text', 'Action label when the item can be added.', true),
('menu_detail_available_label', 'Available', 'Available label', 'text', 'Status label for available items.', true),
('menu_detail_back_to_menu_label', 'Back to menu', 'Back to menu label', 'text', 'Button label returning from the detail page.', true),
('menu_detail_copy', 'Live from the menu.', 'Detail intro copy', 'textarea', 'Short intro copy shown beside the detail hero.', true),
('menu_detail_eyebrow', 'Menu detail', 'Detail eyebrow', 'text', 'Label on the detail page.', true),
('menu_detail_fast_lane_label', 'Fast lane', 'Fast lane label', 'text', 'Label shown when ordering is open.', true),
('menu_detail_hero_copy', 'Live from the menu.', 'Detail hero copy', 'textarea', 'Hero copy on menu detail pages.', true),
('menu_detail_image_url', '', 'Menu detail fallback image', 'image', 'Shown on menu detail pages when an item does not have its own photo.', true),
('menu_detail_live_price_label', 'Live price', 'Live price label', 'text', 'Label for the live price block.', true),
('menu_detail_notice', 'Customizable pizza with live toppings and sizes.', 'Detail notice', 'text', 'Notice text on the detail page.', true),
('menu_detail_one_tap_label', 'One tap to cart', 'One tap label', 'text', 'Support text for the ready-to-add block.', true),
('menu_detail_ordering_paused_label', 'Ordering paused', 'Ordering paused label', 'text', 'State label shown when ordering is paused.', true),
('menu_detail_paused_copy', 'The kitchen is not accepting new orders at the moment.', 'Paused copy', 'textarea', 'Copy shown on detail pages when ordering is paused.', true),
('menu_detail_preview_copy', 'Medium price shown. Use the builder for size and extra control.', 'Detail preview copy', 'textarea', 'Preview card supporting text.', true),
('menu_detail_price_copy', 'Small price to large price', 'Price copy', 'textarea', 'Price card supporting text.', true),
('menu_detail_price_title', 'Price', 'Price title', 'text', 'Price card title.', true),
('menu_detail_ready_to_add_label', 'Ready to add', 'Ready to add label', 'text', 'Label for the ready-to-add block.', true),
('menu_detail_sold_out_label', 'Sold out', 'Sold out label', 'text', 'Status label for sold-out items.', true),
('menu_detail_status_copy', 'Availability follows the live menu state.', 'Status copy', 'textarea', 'Status card supporting text.', true),
('menu_detail_status_first_label', 'Status first', 'Status first label', 'text', 'Label shown when ordering is paused.', true),
('menu_detail_status_paused_label', 'Ordering paused while the storefront is closed or in maintenance mode.', 'Paused status copy', 'textarea', 'Copy shown in the detail status block while paused.', true),
('menu_detail_status_title', 'Status', 'Status title', 'text', 'Status card title.', true),
('menu_detail_view_cart_label', 'View cart', 'View cart label', 'text', 'Button label when ordering is open.', true),
('menu_detail_view_status_label', 'View live status', 'View status label', 'text', 'Button label when ordering is paused.', true),
('menu_empty_closed_action', 'View live status', 'Closed empty action', 'text', 'Action label when the store is closed.', true),
('menu_empty_closed_body', 'The menu is live, but ordering is paused until the store reopens.', 'Closed empty body', 'textarea', 'Body copy when the store is closed.', true),
('menu_empty_matches_body', 'Try a different search term or clear the filters.', 'No matches body', 'textarea', 'Body copy shown when the search returns no results.', true),
('menu_empty_matches_title', 'No matches found', 'No matches title', 'text', 'Title shown when the search returns no results.', true),
('menu_empty_none_title', 'No menu items yet', 'No items title', 'text', 'Title shown when the kitchen has not published items yet.', true),
('menu_empty_open_action', 'Open builder', 'Open empty action', 'text', 'Action label when the store is open but the menu is empty.', true),
('menu_empty_open_body', 'The menu is waiting for the kitchen to publish items.', 'Open empty body', 'textarea', 'Body copy when the store is open but the menu is empty.', true),
('menu_filter_addons_label', 'Addons', 'Addons filter label', 'text', 'Filter chip for addons.', true),
('menu_filter_all_label', 'All', 'All filter label', 'text', 'Filter chip for all items.', true),
('menu_filter_desserts_label', 'Desserts', 'Desserts filter label', 'text', 'Filter chip for desserts.', true),
('menu_filter_extras_label', 'Extras', 'Extras filter label', 'text', 'Filter chip for extras.', true),
('menu_filter_pizzas_label', 'Pizzas', 'Pizzas filter label', 'text', 'Filter chip for pizzas.', true),
('menu_fresh_pairings_copy', 'Everything that makes the pizza sing.', 'Fresh pairings copy', 'textarea', 'Stat card supporting copy for topping counts.', true),
('menu_fresh_pairings_label', 'Fresh pairings', 'Fresh pairings label', 'text', 'Stat card label for topping counts.', true),
('menu_hero_contact_label', 'Contact us', 'Hero contact label', 'text', 'Hero secondary CTA when ordering is paused.', true),
('menu_hero_copy', 'Slide through the menu, find the thing that clicks, and move from discovery to checkout without breaking the mood.', 'Menu hero copy', 'textarea', 'Top subtitle on the menu page.', true),
('menu_hero_eyebrow', 'Tonight''s selection', 'Hero eyebrow', 'text', 'Eyebrow at the top of the menu hero.', true),
('menu_hero_image_url', '', 'Menu hero image', 'image', 'Shown beside the menu intro and browsing summary.', true),
('menu_hero_open_builder_label', 'Open Builder', 'Hero open builder', 'text', 'Hero CTA when ordering is open.', true),
('menu_hero_preview_fallback_alt', 'Live menu', 'Hero fallback alt', 'text', 'Alt text when the menu hero preview image is missing.', true),
('menu_hero_preview_fallback_copy', 'A signature bite from the kitchen right now.', 'Hero fallback copy', 'textarea', 'Fallback copy shown in the menu hero preview.', true),
('menu_hero_preview_fallback_title', 'Chef Special', 'Hero fallback title', 'text', 'Fallback title shown in the menu hero preview.', true),
('menu_hero_review_cart_label', 'Review Cart', 'Hero review cart', 'text', 'Hero secondary CTA when ordering is open.', true),
('menu_hero_title', 'A menu that feels like a craving, not a catalog.', 'Menu hero title', 'text', 'Top title on the menu page.', true),
('menu_hero_view_status_label', 'View live status', 'Hero view status', 'text', 'Hero CTA when ordering is paused.', true),
('menu_ingredient_nonveg_label', 'Non-veg ingredient', 'Non-veg ingredient label', 'text', 'Label used for non-veg toppings.', true),
('menu_ingredient_veg_label', 'Vegetarian ingredient', 'Veg ingredient label', 'text', 'Label used for vegetarian toppings.', true),
('menu_learn_more_label', 'Learn more', 'Learn more label', 'text', 'Link label in empty menu states.', true),
('menu_pairings_copy', 'Toppings are shown as a live ingredient library so customers can see what rounds out the menu.', 'Pairings copy', 'textarea', 'Supporting copy for the toppings grid.', true),
('menu_pairings_eyebrow', 'Pairings', 'Pairings eyebrow', 'text', 'Eyebrow above the toppings grid.', true),
('menu_pairings_none_copy', 'The kitchen has not published pairings yet. Once they do, they will appear here.', 'Pairings empty copy', 'textarea', 'Body copy shown when no toppings are available.', true),
('menu_pairings_none_title', 'No pairings yet', 'Pairings empty title', 'text', 'Title shown when no toppings are available.', true),
('menu_pairings_title', 'The little things that complete the bite', 'Pairings title', 'text', 'Title above the toppings grid.', true),
('menu_pizza_moods_copy', 'Each one is a different craving lane.', 'Pizza moods copy', 'textarea', 'Stat card supporting copy for pizza categories.', true),
('menu_pizza_moods_label', 'Pizza moods', 'Pizza moods label', 'text', 'Stat card label for pizza categories.', true),
('menu_search_label', 'Search', 'Search label', 'text', 'Label above the search field.', true),
('menu_search_placeholder', 'Search by craving, topping, or favorite', 'Search placeholder', 'text', 'Placeholder text for the menu search field.', true),
('menu_section_copy', 'Search the live menu and add items with one tap. Pizzas can also be customized in the builder.', 'Browse copy', 'textarea', 'Section copy above menu filters.', true),
('menu_section_eyebrow', 'Browse the menu', 'Section eyebrow', 'text', 'Label above the menu browser section.', true),
('menu_section_title', 'Find the thing that feels right', 'Browse title', 'text', 'Section title above menu filters.', true),
('menu_whats_showing_copy', 'A live selection from the kitchen.', 'What''s showing copy', 'textarea', 'Stat card supporting copy for the live menu count.', true),
('menu_whats_showing_label', 'What''s showing', 'What''s showing label', 'text', 'Stat card label for the live menu count.', true),
('min_order_amount', '0', 'Minimum order', 'number', 'Shown in cart and delivery pages.', true),
('nav_links', '[{"href":"/home","label":"Home"},{"href":"/menu","label":"Menu"},{"href":"/build","label":"Build"},{"href":"/cart","label":"Cart"},{"href":"/about","label":"About"},{"href":"/contact","label":"Contact"}]', 'Navigation links', 'json', 'Primary site navigation', true),
('not_found_copy', 'The link may be outdated or the page may not exist yet. The menu and checkout are still ready.', '404 copy', 'textarea', 'Body copy on the not-found page.', true),
('not_found_eyebrow', '404', '404 eyebrow', 'text', 'Eyebrow on the not-found page.', true),
('not_found_primary_cta', 'Back to menu', '404 primary CTA', 'text', 'Primary action on the not-found page.', true),
('not_found_secondary_cta', 'Go home', '404 secondary CTA', 'text', 'Secondary action on the not-found page.', true),
('not_found_title', 'We could not find that page.', '404 title', 'text', 'Title on the not-found page.', true),
('opening_time', '11:00', 'Opening time', 'time', 'Opening time used across the storefront.', true),
('privacy_back_to_menu_label', 'Back to menu', 'Privacy back button', 'text', 'Button label returning to the menu from the Privacy page.', true),
('privacy_eyebrow', 'Privacy', 'Privacy eyebrow', 'text', 'Eyebrow shown on the Privacy page.', true),
('privacy_hero_copy', 'The storefront stores customer and order details in Supabase so the kitchen can fulfill, track, and review orders.', 'Privacy hero copy', 'textarea', 'Privacy page supporting copy.', true),
('privacy_hero_title', 'We only keep what we need to fulfill the order.', 'Privacy hero title', 'text', 'Privacy page title.', true),
('privacy_sections', '[{"title":"Order storage","body":"Order content is persisted to the database before the handoff step."},{"title":"Usage","body":"We use the data to fulfill the order and improve service operations."},{"title":"Retention","body":"Retention policy can be formalized in the admin config or a legal page later."}]', 'Privacy Sections', 'json', 'Structured privacy blocks', true),
('shell_cart_aria_label_template', 'Cart with {count} items', 'Cart aria template', 'text', 'Accessible cart label with a count placeholder.', true),
('shell_close_navigation_label', 'Close navigation menu', 'Close nav label', 'text', 'Button label for closing the mobile navigation drawer.', true),
('shell_hours_label', 'Hours', 'Hours label', 'text', 'Footer label for operating hours.', true),
('shell_live_label', 'Live', 'Live label', 'text', 'Text used when the dashboard is live.', true),
('shell_location_label', 'Location', 'Location label', 'text', 'Drawer label for the location block.', true),
('shell_mobile_navigation_label', 'Mobile navigation', 'Mobile nav label', 'text', 'Accessible label for the mobile navigation region.', true),
('shell_open_navigation_label', 'Open navigation menu', 'Open nav label', 'text', 'Button label for opening the mobile navigation drawer.', true),
('shell_order_chat_label', 'Order chat', 'Order chat label', 'text', 'Drawer label for the direct order phone number.', true),
('shell_order_label', 'Order', 'Order label', 'text', 'Footer label for the order channel.', true),
('shell_paused_label', 'Paused', 'Paused label', 'text', 'Text used when the dashboard is not live.', true),
('shell_primary_nav_label', 'Primary', 'Primary nav label', 'text', 'Accessible label for the desktop navigation.', true),
('shell_sync_label', 'Control room sync', 'Sync label', 'text', 'Footer label before the live/paused indicator.', true),
('site_maintenance_mode', 'false', 'Maintenance Mode', 'boolean', 'Put the storefront into maintenance for all users.', true),
('site_meta_description', 'An editorial pizza storefront with live menu data, WhatsApp ordering, and a premium customer experience.', 'SEO description', 'textarea', 'Browser description used by search engines.', true),
('site_meta_title', 'We Knead Pizza | Crafted Pizza Ordering', 'SEO title', 'text', 'Browser title and metadata title.', true),
('site_theme_color', '#050403', 'Theme color', 'text', 'Browser theme color in hex format.', true),
('size_large_label', 'L', 'Large label', 'text', 'Short size label for the large pizza size.', true),
('size_large_name', 'Large', 'Large name', 'text', 'Full name for the large pizza size.', true),
('size_medium_label', 'M', 'Medium label', 'text', 'Short size label for the medium pizza size.', true),
('size_medium_name', 'Medium', 'Medium name', 'text', 'Full name for the medium pizza size.', true),
('size_small_label', 'S', 'Small label', 'text', 'Short size label for the small pizza size.', true),
('size_small_name', 'Small', 'Small name', 'text', 'Full name for the small pizza size.', true),
('status_eyebrow', 'Live status', 'Status eyebrow', 'text', 'Eyebrow shown on the Status page.', true),
('status_hero_copy', 'This status follows the live settings and is what the storefront will show before checkout.', 'Status hero copy', 'textarea', 'Status page hero copy.', true),
('status_hours_copy', 'Update hours in the store settings.', 'Status hours copy', 'textarea', 'Status hours card copy.', true),
('status_hours_title', 'Hours', 'Status hours title', 'text', 'Status hours card title.', true),
('status_path_copy', 'Menu -> cart -> WhatsApp.', 'Status path copy', 'textarea', 'Status order path card copy.', true),
('status_path_title', 'Order path', 'Status path title', 'text', 'Status order path card title.', true),
('status_state_closed_label', 'Closed', 'Status closed label', 'text', 'Status value shown when the store is closed.', true),
('status_state_copy', 'The state is live from the store settings.', 'Status state copy', 'textarea', 'Status card copy for the live state.', true),
('status_state_maintenance_label', 'Maintenance', 'Status maintenance label', 'text', 'Status value shown during maintenance mode.', true),
('status_state_open_label', 'Open', 'Status open label', 'text', 'Status value shown when the store is open.', true),
('status_state_title', 'State', 'Status state title', 'text', 'Status card title for the live state.', true),
('status_title_closed', 'We are closed right now.', 'Status closed title', 'text', 'Live status page title when closed.', true),
('status_title_maintenance', 'Maintenance mode is active.', 'Status maintenance title', 'text', 'Live status page title during maintenance.', true),
('status_title_open', 'We are open.', 'Status open title', 'text', 'Live status page title when open.', true),
('store_name', 'We Knead Pizza', 'Store name', 'text', 'Primary brand name across the storefront.', true),
('storefront_closed_label', 'Closed', 'Closed badge label', 'text', 'Badge shown when the storefront is closed.', true),
('storefront_closed_primary_label', 'View status', 'Closed primary button', 'text', 'Primary action shown when the storefront is closed.', true),
('storefront_closed_secondary_label', 'Browse menu', 'Closed secondary button', 'text', 'Secondary action shown when the storefront is closed.', true),
('storefront_closed_summary', 'Orders are closed right now. Browse the menu and check the live status for the next open window.', 'Closed summary', 'textarea', 'Summary shown when the storefront is closed.', true),
('storefront_maintenance_label', 'Maintenance mode', 'Maintenance badge label', 'text', 'Badge shown when the storefront is in maintenance.', true),
('storefront_maintenance_primary_label', 'View status', 'Maintenance primary button', 'text', 'Primary action shown during maintenance.', true),
('storefront_maintenance_secondary_label', 'Contact us', 'Maintenance secondary button', 'text', 'Secondary action shown during maintenance.', true),
('storefront_maintenance_summary', 'The storefront is being updated. Browsing still works, but checkout is paused until maintenance ends.', 'Maintenance summary', 'textarea', 'Summary shown when the storefront is in maintenance.', true),
('storefront_open_label', 'Open now', 'Open badge label', 'text', 'Badge shown when the storefront is open.', true),
('storefront_open_primary_label', 'View cart', 'Open primary button', 'text', 'Primary action shown when the storefront is open.', true),
('storefront_open_secondary_label', 'Browse menu', 'Open secondary button', 'text', 'Secondary action shown when the storefront is open.', true),
('storefront_open_summary', 'Orders are live now. Checkout is available and the live window is 11:00 - 23:00.', 'Open summary', 'textarea', 'Summary shown when the storefront is open.', true),
('support_email', 'hello@wkp.local', 'Support email', 'text', 'Displayed on the Contact page.', true),
('terms_contact_us_label', 'Contact us', 'Terms contact button', 'text', 'Button label returning to contact from the Terms page.', true),
('terms_eyebrow', 'Terms', 'Terms eyebrow', 'text', 'Eyebrow shown on the Terms page.', true),
('terms_hero_copy', 'Placing an order means the kitchen may contact you through WhatsApp to confirm details or delivery timing.', 'Terms hero copy', 'textarea', 'Terms page supporting copy.', true),
('terms_hero_title', 'Plain terms for a straightforward order flow.', 'Terms hero title', 'text', 'Terms page title.', true),
('terms_sections', '[{"title":"Order confirmation","body":"The handoff channel is the primary confirmation path for all orders."},{"title":"Accuracy","body":"Please check address, phone, and item details before sending."},{"title":"Availability","body":"All menu availability and prices are controlled from the store settings."}]', 'Terms Sections', 'json', 'Structured terms blocks', true),
('whatsapp_number', '918484802540', 'WhatsApp number', 'text', 'Used for order handoff and quick contact.', true)
on conflict (key) do update set
  value = excluded.value,
  label = excluded.label,
  type = excluded.type,
  description = excluded.description,
  is_public = excluded.is_public;